name: charts_painter
description: Highly customizable and extendable charts library for flutter made with custom painters
version: 3.0.0
homepage: https://github.com/infinum/flutter-charts
repository: https://github.com/infinum/flutter-charts

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  golden_toolkit: ^0.13.0
  lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true